### ISSUE TITLE
Crash if no databinding enabled in project

### ISSUE THREAD

**Issue by Dimezis** [lyrebirdstudio/Croppy#24]
Crash when starting Croppy if the project doesn't have databinding added in gradle.

```Kotlin
Croppy.start(this, CropRequest.Auto(bitmapUri, code))
```
```
FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at com.lyrebirdstudio.croppylib.main.CroppyActivity.onCreate(CroppyActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by HaXxanParhar** [comment]
I faced the same issue so ended up enabling the data binding by adding the following:

   buildFeatures {
        dataBinding true
}

Do you have a specific reason for not adding the data binding?

**Comment by Dimezis** [comment]
> Do you have a specific reason for not adding the data binding?

Well, if data binding is not used in the project, why force it?
It would affect build times and add unnecessary dependencies
